### ISSUE TITLE
同期再生に向けた`EXT-X-PROGRAM-DATE-TIME`タグの使用方法を調査

### ISSUE THREAD

**Issue by Be3751** [Be3751/sync-multi-movie#1]
### 概要
以下のような内容で`EXT-X-PROGRAM-DATE-TIME`タグが同期再生に使えることが分かっているものの、`EXT-X-PROGRAM-DATE-TIME`タグの定義やHLSの仕組みとして配信にどう作用するのかが分からないので、このIssueで情報を整理する。
> 1. Playback is synchronized using shared EXT-X-PROGRAM-DATE-TIME tags（WWDC2017）
> 2. 同期再生にはHLSの`EXT-X-PROGRAM-DATE-TIME`タグを使う（FromAtomさんの公演）

### 今、気になっていること（随時更新してOK）
- `EXT-X-PROGRAM-DATE-TIME`タグの定義
- `EXTINF`タグの定義
- 配信中のプレイリストの更新は、配信内容に作用するのか？

### 意識したいこと
- 出典込みで確定した内容を記載する（公式ドキュメントやRFCなどを推奨）
- お互い出し合った情報に曖昧な部分や新たに出てきた疑問があれば、きちんと伝える（MTG時でもこのIssueでもOK）

**Comment by Be3751** [comment]
EXT-X-PROGRAM-DATE-TIMEタグの定義

**Comment by Be3751** [comment]
配信中のプレイリストの更新は、配信内容に作用するのか？

**Comment by Be3751** [comment]
### 分かったこと


### 出典

**Comment by kabigon-1015** [comment]
## EXT-X-PROGRAM-DATE-TIMEタグの定義
### わかったこと
- メディアセグメントの最初のサンプルに絶対日時（日付と時刻）を関連付け
- 次のメディアセグメントにのみ適用（タグのある行の次の行にあるメディアセグメントだけってこと？）
- 各メディアセグメントで記述
- タイムゾーンと秒の小数部をミリ秒の精度で示す必要あり
  - ex）`#EXT-X-PROGRAM-DATETIME:2023-06-04T01:57:30.000+09:00`
- タグで指定された（壁時計）日時のセグメント内の最初のメディアタイムスタンプへの有益なマッピングを定義
  - シーク、表示、またはその他の目的の基礎として使用可能

### 出典
- https://tex2e.github.io/rfc-translater/html/rfc8216.html#4-3-2-6--EXT-X-PROGRAM-DATE-TIME
- https://tex2e.github.io/rfc-translater/html/rfc8216.html#6-2-1--General-Server-Responsibilities

**Comment by Be3751** [comment]
## 配信中のプレイリストの更新や更新による作用について
### 分かったこと
- プレイリストファイルへの変更は、クライアントの観点からアトミックに行う必要あり
- そうしない場合、再生エラーが発生する可能性
- サーバーは、以下の操作を除いて、メディアプレイリストファイルへの変更は不可
  - 行の追加（セクション6.2.1）。
  - メディアセグメントURIを表示順にプレイリストから削除し、それらのセグメントにのみ適用されるタグを追加（Section 6.2.2）
  - `EXT-X-MEDIA-SEQUENCE`タグまたは`EXT-X-DISCONTINUITY-SEQUENCE`タグの値を増加（Section 6.2.2）
  - `EXT-X-ENDLIST`タグをプレイリストに追加（Section 6.2.1）

### 出典
- https://tex2e.github.io/rfc-translater/html/rfc8216.html#6-2-1--General-Server-Responsibilities

**Comment by Be3751** [comment]
## EXT-X-PROGRAM-DATE-TIMEタグについてその他の情報
### 分かったこと
- サーバーがこのマッピングを提供する場合、サーバーは`EXT-X-DISCONTINUITY`タグが適用されているすべてのセグメントに`EXT-X-PROGRAM-DATE-TIME`タグを適用する必要あり
- プログラムの日付とメディアセグメントの間のマッピングがあいまいになるプレイリストに、`EXT-X-PROGRAM-DATE-TIME`タグの追加は不可
- `EXT-X-PROGRAM-DATE-TIME`タグの値にタイムゾーン情報が含まれている場合、クライアントはそれを考慮に入れる必要あり
  - そうでない場合、クライアントはローカル時間であると見なす場合あり
- プレイリストの日付は、コンテンツが作成された日時（または他の日時）を指す場合があり、再生時間とは関係がないことに注意
- If the first EXT-X-PROGRAM-DATE-TIME tag in a Playlist appears after one or more Media Segment URIs, the client SHOULD extrapolate backward from that tag (using EXTINF durations and/or media timestamps) to associate dates with those segments.
- To associate a date with any other Media Segment that does not have an EXT-X-PROGRAM-DATE-TIME tag applied to it directly, the client SHOULD extrapolate forward from the last EXT-X-PROGRAM-DATE-TIME tag appearing before that segment in the Playlist.

### 出典
- https://tex2e.github.io/rfc-translater/html/rfc8216.html#6-2-1--General-Server-Responsibilities
- https://tex2e.github.io/rfc-translater/html/rfc8216.html#6-3-3--Playing-the-Media-Playlist-File

**Comment by Be3751** [comment]
## EXTINFタグの定義
### 分かったこと
- このタグは、メディアセグメントの期間を指定
- メディアセグメントごとに必要
- 形式: #EXTINF:<duration>,[<title>]
  - dutaion: メディアセグメントの期間を秒単位で指定する10進浮動小数点数または10進整数
    - ただし、互換バージョン番号が3未満の場合、期間は整数でなければならない
    - 整数として報告される期間は、最も近い整数に丸める必要あり
  -  title: UTF-8テキストとして表現された、メディアセグメントのオプションの人間が読める情報

### 出典
- https://tex2e.github.io/rfc-translater/html/rfc8216.html#4-3-2-1--EXTINF

**Comment by Be3751** [comment]
## HLSによる動画のシーク方法について
### 分かったこと
- シーク自体はcurrentTimeプロパティの更新によって行うもの
  - [HTMLMediaElement](https://developer.mozilla.org/ja/docs/Web/API/HTMLMediaElement) インターフェイスの currentTime プロパティは、現在の再生時間を秒単位で示す
  - この値を変更すると、メディアは新しい時刻にシークされます。
- `EXT-X-PROGRAM-DATE-TIME`タグは同期再生のための遅延時間を算出するために使う必要がありそう（個人的見解）
  - RFCには、`EXT-X-PROGRAM-DATE-TIME`タグが再生時刻を示すものとして記載されている箇所が見当たらなかったため

### 出典
- https://developer.mozilla.org/ja/docs/Web/API/HTMLMediaElement/currentTime
